--Hi, Thanks for using the GUI.
--These are the Steps u need to Follow for the GUI to work.
--Also do not Change anything on the Scripts or the GUI will Break.
--Also Delete the Brick "[Delete Me]".

--1. Put the Blur In Lighting.

--2. Put the "GUI" In the StarterGUI.

--3. Open the "GUI" and open "Frame"

--4. "Frame 1" is the Frame for the Endings.

--5. "Frame 2" is the Frame for the Credits.

--6. Open the Properties of the "Frame 1" or "Frame 2" and Enable  Visible.

--7. Change Things in the "Frame 1" and "Frame 2" Frames How u want

--8. When u are done Changeing "Frame 1" and "Frame 2" then go to the Properties again and Disable Visible.

--9. You can also Change the TextLabels of the GUI.

--10. If you Done all the Steps then, Contratilations you Suceesfully made the GUI for the Game.







--Made by ZugLOLGamer :P
